/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CastlesOfBurgundyRouteImport } from './routes/castles-of-burgundy'
import { Route as IndexRouteImport } from './routes/index'

const CastlesOfBurgundyRoute = CastlesOfBurgundyRouteImport.update({
  id: '/castles-of-burgundy',
  path: '/castles-of-burgundy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/castles-of-burgundy': typeof CastlesOfBurgundyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/castles-of-burgundy': typeof CastlesOfBurgundyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/castles-of-burgundy': typeof CastlesOfBurgundyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/castles-of-burgundy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/castles-of-burgundy'
  id: '__root__' | '/' | '/castles-of-burgundy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CastlesOfBurgundyRoute: typeof CastlesOfBurgundyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/castles-of-burgundy': {
      id: '/castles-of-burgundy'
      path: '/castles-of-burgundy'
      fullPath: '/castles-of-burgundy'
      preLoaderRoute: typeof CastlesOfBurgundyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CastlesOfBurgundyRoute: CastlesOfBurgundyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
